steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
   args:
      - --destination=gcr.io/$PROJECT_ID/$_SERVICE_NAME-image
      - --cache=true
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      [
        'run',
        'services',
        'update',
        '$_SERVICE_NAME',
        '--platform=managed',
        '--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME-image',
        '--region=us-central1',
        '--quiet'
      ]
