steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/template-typescript-monorepo-image
      - --cache=true
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      [
        'run',
        'services',
        'update',
        'template-typescript-monorepo',
        '--platform=managed',
        '--image=gcr.io/$PROJECT_ID/template-typescript-monorepo-image',
        '--region=us-central1',
        '--quiet'
      ]
