# .github/actions/setup-node/action.yml
name: 'install workspace'
description: 'Set up Bun and install packages'
runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: bun install
      run: bun install --silent
      shell: bash
