# .github/actions/setup-node/action.yml
name: 'install workspace'
description: 'Set up Node.js environment and check out code'
inputs:
  node-version-file:
    description: 'Path to Node version file'
    default: '.nvmrc'
  pnpm-version:
    description: 'Path to Node version file'
    default: 10.2.1

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version:  ${{ inputs.pnpm-version }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version-file }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
        