name: deploy-cloud-run
description: 'Build, Push and Deploy to Google Cloud Run'
inputs:
  project_id:
    description: 'Google Cloud Project ID'
    required: true
  service_name:
    description: 'Google Cloud Run Service Name'
    required: true
  credentials_json:
    description: 'Google Cloud Service Account JSON'
    required: true
  gcr_hostname:
    description: 'Google Cloud Run Docker Repository'
    required: false
    default: gcr.io
  dockerfile:
    description: 'Location of Dockerfile'
    required: true
    default: ./Dockerfile
  dry_run:
    description: 'If set to true, skips the deployment step'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - id: 'auth'
      name: gcloud auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ inputs.credentials_json }}'

    - name: echo
      run: echo Run run ${{ inputs.dry_run }}
      shell: bash

    - name: gcloud sdk
      uses: google-github-actions/setup-gcloud@v2
      with:
        skip_install: true

    - name: docker build
      run: |
        docker build -t ${{ inputs.gcr_hostname }}/${{ inputs.project_id }}/${{ inputs.service_name }}:${{ github.sha }} -f ${{ inputs.dockerfile }} .
      shell: bash

    - name: docker push
      run: |
        gcloud auth configure-docker
        docker push ${{ inputs.gcr_hostname }}/${{ inputs.project_id }}/${{ inputs.service_name }}:${{ github.sha }}
      shell: bash

    - name: gcloud run deploy
      if: ${{ inputs.dry_run }} == 'false'
      run: |
        gcloud run deploy ${{ inputs.service_name }} \
        --image ${{ inputs.gcr_hostname }}/${{ inputs.project_id }}/${{ inputs.service_name }}:${{ github.sha }} \
        --platform managed \
        --region us-central1 \
        --quiet
      shell: bash
