name: deploy-cloud-run
description: 'Build, Push and Deploy to Google Cloud Run'
inputs:
  project_id:
    description: 'Google Cloud Project ID'
    required: true
  service_name:
    description: 'Google Cloud Run Service Name'
    required: true
  credentials_json:
    description: 'Google Cloud Service Account JSON'
    required: true
  gar_hostname:
    description: 'Google Artifact Registry hostname'
    required: true
    default: us-central1-docker.pkg.dev
  rollbar_access_token:
    description: 'Rollbar Access Token'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ inputs.credentials_json }}'

    - uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ inputs.service_name }}
        image: ${{ inputs.gar_hostname }}/${{ inputs.project_id }}/shared-docker-registry/${{ inputs.service_name }}:${{ github.sha }}

    - uses: rollbar/github-deploy-action@2.1.2
      if: ${{ inputs.rollbar_access_token != '' }}
      with:
        environment: 'production'
        version: ${{ github.sha }}
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ inputs.rollbar_access_token }}
        ROLLBAR_USERNAME: ${{ github.actor }}
