name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: bun install
        run: bun install --silent

      - name: bun run build
        run: bun run build

  test:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: bun install
        run: bun install --silent

      - name: bun run test
        env:
          TEST_PUBLIC_TOKEN: ${{ secrets.TEST_PUBLIC_TOKEN }}
          TEST_PRIVATE_TOKEN: ${{ secrets.TEST_PRIVATE_TOKEN }}
        run: bun run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: bun install
        run: bun install --silent

      - name: bun run lint
        run: bun run lint
