name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: install workspace
        uses: ./.github/actions/install-workspace

      - name: npm run build
        run: npm run build

  test:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: install workspace
        uses: ./.github/actions/install-workspace

      - name: npm test
        env:
          TEST_PUBLIC_TOKEN: ${{ secrets.TEST_PUBLIC_TOKEN }}
          TEST_PRIVATE_TOKEN: ${{ secrets.TEST_PRIVATE_TOKEN }}
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: install workspace
        uses: ./.github/actions/install-workspace

      - name: npm run lint
        run: npm run lint
