name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: init node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

  test:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #
      #- uses: 'google-github-actions/auth@v2'
      #  with:
      #    project_id: 'bhouston-innovation'
      #    service_account: 'threekit-packages@bhouston-innovation.iam.gserviceaccount.com'
      #    workload_identity_provider: 'projects/150631667524/locations/global/workloadIdentityPools/github/providers/threekit-packages'

      - name: init node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: npm ci
        run: npm ci

      - name: npm test
        env:
          TEST_PUBLIC_TOKEN: ${{ secrets.TEST_PUBLIC_TOKEN }}
          TEST_PRIVATE_TOKEN: ${{ secrets.TEST_PRIVATE_TOKEN }}
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: init node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint
