name: deploy

on:
  push:
    branches:
      - main # or any other branch you want to deploy from

env:
  PROJECT_ID: bhouston-general-hosting
  SERVICE_NAME: template-typescript-monorepo
  GCR_HOSTNAME: gcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: deploy cloud run
        uses: ./.github/actions/deploy-cloud-run
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          service_name: ${{ env.SERVICE_NAME }}
          gcr_hostname: ${{ env.GCR_HOSTNAME }}
